Output kuzco_demo.gif

Set WindowBar Colorful
Set Margin 20
Set MarginFill "#000000"
Set TypingSpeed 75ms
Set BorderRadius 10
Set Width 1300
Set Height 650
Set FontSize 16

Type "# Kuzco intelligently analyzes Terraform configurations using your local LLMs
Sleep 1s
Enter
Type "# Let's try it out!"
Sleep 1s
Enter
Hide
Type "clear"
Enter
Show
Type@100ms "kuzco --file modules/s3-bucket.tf --model PE7B"
Enter
Sleep 10s

