name: "Build CLI and Attach to GitHub Release"

on:
  release:
    types: [published]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    name: "Build CLI and Attach to GitHub Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Go
      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      # Print Go version
      - run: go version

      # Build and release
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --parallelism 2 --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Get Debian Package Names
        id: deb_package
        run: |
          echo "ARM_PACKAGE=$(find dist/ -name '*arm64.deb' | head -n 1)" >> $GITHUB_ENV
          echo "AMD_PACKAGE=$(find dist/ -name '*amd64.deb' | head -n 1)" >> $GITHUB_ENV

      # Push the Debian package to Cloudsmith
      - name: Push Debian ARM package to Cloudsmith
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "rosesecurity"
          repo: "kuzco"
          distro: "any-distro"
          release: "any-version"
          file: ${{ env.ARM_PACKAGE }}

      - name: Push Debian AMD package to Cloudsmith
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "rosesecurity"
          repo: "kuzco"
          distro: "any-distro"
          release: "any-version"
          file: ${{ env.AMD_PACKAGE }}

